// Spanish Buzzer Game — class question bank
// 50 questions total: DOPs (1-15), IDOPs (16-30), mixed (31-50)
export const QUESTIONS: string[] = [
  // DOPs
  "Yo como la manzana.",
  "Él lee el libro.",
  "Nosotros compramos los boletos.",
  "Ellas miran las fotos.",
  "¿Tú tienes la llave?",
  "Juan visita a nosotros.",
  "Ustedes beben el café.",
  "Yo quiero a ti.",
  "Marta hace la tarea.",
  "Nosotros escuchamos la música.",
  "Ellos venden el carro.",
  "¿Ves a los niños?",
  "Cocino la cena.",
  "Limpio los platos.",
  "Ella trae sus gafas.",
  // IDOPs
  "Doy el regalo a María.",
  "Escribo una carta a mis padres.",
  "Ella explica la lección a nosotros.",
  "¿Pides dinero a tu hermano?",
  "Ellos sirven la comida a los clientes.",
  "Yo compro dulces para ti.",
  "El profesor dice la verdad a los estudiantes.",
  "Mandamos el paquete a Juan.",
  "Mi madre lee un cuento a mí.",
  "Traigo las flores a mi abuela.",
  "Vendes el coche a nosotros.",
  "Presto mi lápiz a Pedro.",
  "Muestro el mapa a la turista.",
  "Cocinamos para ellos.",
  "Dices el secreto a ella.",
  // Mixed
  "Yo te doy el libro.",
  "Él nos vende la casa.",
  "Ella escribe una carta a Juan.",
  "Yo mando el regalo a ti.",
  "Nosotros servimos la sopa a los niños.",
  "Tú compras las flores para ella.",
  "Ustedes dan los premios a nosotros.",
  "Yo pido la cuenta al mesero.",
  "Ellos traen los documentos a usted.",
  "Marta explica el problema a mí.",
  "Tú entregas el examen al profesor.",
  "Nosotros mostramos las fotos a ustedes.",
  "Yo digo la verdad a ellos.",
  "Ella presta su bici a su amiga.",
  "¿Me pasas la sal?",
  "Voy a dar el dinero a ti.",
  "Ellas quieren decir la noticia a nosotros.",
  "Estamos sirviendo el postre a los invitados.",
  "Danos las llaves.",
  "Escribe el mensaje a ella.",
];
